# Generated by Django 4.0.4 on 2022-06-09 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': '2_Author'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '2_Book'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': '2_Member'},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'verbose_name': '1_Book'},
        ),
        migrations.AlterModelOptions(
            name='writer',
            options={'verbose_name': '1_Author'},
        ),
        migrations.AddField(
            model_name='like',
            name='content_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='object_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
