# Generated by Django 4.0.4 on 2022-06-09 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_author_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '3_Article'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '3_Comment'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': '3_Like'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '3_User'},
        ),
    ]
